### ISSUE TITLE
Breaking Issue Fix

### ISSUE THREAD

**Issue by iDutchy** [fwizzz/Command-maker-bot#1]
Ok, so it has come to my notice there are some huge flaws in this code. There is a lot that could be improved! Now, with my method this will be a very simple and quick process. It'll only take a few minutes!

- Delete the bot

This should fix all the current issues. Please consider my solution, it should fix many issues!

Thank you,
~ Dutchy

**Comment by fvviz** [comment]
ok i will get to it as soon as possible

**Comment by rodovia** [comment]
dutchy is right not gonna lie

**Comment by darealzz** [comment]
This issue is very annoying. Please resolve this ASAP.

May I suggest, deleting the entire bots application.

Thank you,
~ dareal
